from typing import Any

class TriggerMessage:
    def __init__(self, **kwargs: Any) -> None: ...

class Reset:
    def __init__(self, **kwargs: Any) -> None: ...

class RemoteStartTransaction:
    def __init__(self, **kwargs: Any) -> None: ...

class RemoteStopTransaction:
    def __init__(self, **kwargs: Any) -> None: ...

class UnlockConnector:
    def __init__(self, **kwargs: Any) -> None: ...

class ChangeAvailability:
    def __init__(self, **kwargs: Any) -> None: ...

class GetDiagnostics:
    def __init__(self, **kwargs: Any) -> None: ...

class UpdateFirmware:
    def __init__(self, **kwargs: Any) -> None: ...
