from typing import Any

class TriggerMessage:
    def __init__(self, **kwargs: Any) -> None: ...

class Reset:
    def __init__(self, **kwargs: Any) -> None: ...

class RequestStartTransaction:
    def __init__(self, **kwargs: Any) -> None: ...

class RequestStopTransaction:
    def __init__(self, **kwargs: Any) -> None: ...

class UnlockConnector:
    def __init__(self, **kwargs: Any) -> None: ...

class ChangeAvailability:
    def __init__(self, **kwargs: Any) -> None: ...

class GetLog:
    def __init__(self, **kwargs: Any) -> None: ...

class UpdateFirmware:
    def __init__(self, **kwargs: Any) -> None: ...
